# Pin specific version
# use the slim for reduce image size
FROM node:19.6-bullseye-slim

# Specify working directory other than /
WORKDIR /usr/src/app

COPY . .

RUN npm install

CMD ["node" , "src/index.js"]
