# Pin specific version for stability
# Use slim for reduced image size
FROM node:18-alpine

# Specify working directory other than /
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./

RUN npm install

# Use non-root user
# Use --chown on COPY commands to set file permissions
USER node

# Copy remaining source code AFTER installing dependecies.
# Again, copy only the necessary files
COPY --chown=node:node ./src/ ./

EXPOSE 3000

CMD ["node", "index.js"]