# Pin specific version for stability
# Use LTS alpine for smaller image size
FROM node:18-alpine

# Set NODE_ENV
ENV NODE_ENV=production

# Specify working directory other than /
WORKDIR /usr/src/app

# Copy only files required to install
# dependencies (better layer caching)
COPY package*.json ./

# Install only production dependencies
RUN npm ci --only=production

# Use non-root user
# Use --chown on COPY commands to set file permissions
USER node


# Copy remaining source code AFTER installing dependecies.
# Again, copy only the necessary files
COPY --chown=node:node ./src/ ./

EXPOSE 3000

CMD [ "node", "index.js" ]